name: mediasoup-client-aiortc

on: [pull_request, workflow_dispatch]

concurrency:
  # Cancel a currently running workflow from the same PR, branch or tag when a
  # new workflow is triggered.
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        ci:
          - os: ubuntu-20.04
            node: 16
          - os: ubuntu-20.04
            node: 18
          - os: ubuntu-22.04
            node: 20
          - os: macos-12
            node: 20
          - os: windows-2022
            node: 20

    runs-on: ${{ matrix.ci.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.ci.node }}

      - name: Configure cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
          key: ${{ matrix.ci.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ matrix.ci.os }}-node-

      - name: npm ci
        run: npm ci --force --foreground-scripts

      # NOTE: Avoid lint:python due to
      # https://github.com/versatica/mediasoup-client-aiortc/issues/25
      - name: npm run lint:node
        run: npm run lint:node

      - name: npm run test
        run: DEBUG="mediasoup-client-aiortc:WARN* mediasoup-client-aiortc:ERROR*" PYTHON_LOG_TO_STDOUT=true npm run test
